application1.properties

management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*
management.endpoint.health.enabled=true
management.endpoint.health.probes.enabled=true


application2.properties

server.port=8081
spring.application.name=application2
server.servlet.context-path=/application2
url=http://localhost:8081/application2

